CREATE TABLE "pushup_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pushup_habit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pushup_habit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"goal" text NOT NULL,
	"description" text,
	"user_id" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pushup_habit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pushup_habit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"habit_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"checkin_date" date NOT NULL,
	"completed" boolean NOT NULL,
	"action_taken" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pushup_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "pushup_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "pushup_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"role" text,
	"banned" boolean,
	"ban_reason" text,
	"ban_expires" timestamp,
	CONSTRAINT "pushup_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "pushup_user_stats" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"current_streak" integer DEFAULT 0,
	"longest_streak" integer DEFAULT 0,
	"total_consistent_days" integer DEFAULT 0,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "pushup_user_stats_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "pushup_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "pushup_account" ADD CONSTRAINT "pushup_account_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD CONSTRAINT "pushup_habit_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD CONSTRAINT "pushup_habit_log_habit_id_pushup_habit_id_fk" FOREIGN KEY ("habit_id") REFERENCES "public"."pushup_habit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD CONSTRAINT "pushup_habit_log_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_session" ADD CONSTRAINT "pushup_session_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_user_stats" ADD CONSTRAINT "pushup_user_stats_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "habit_name_idx" ON "pushup_habit" USING btree ("name");--> statement-breakpoint
CREATE INDEX "habit_log_habit_id_idx" ON "pushup_habit_log" USING btree ("habit_id");--> statement-breakpoint
CREATE INDEX "email_idx" ON "pushup_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "userstats_leaderboard_idx" ON "pushup_user_stats" USING btree ("current_streak" DESC NULLS LAST,"longest_streak" DESC NULLS LAST);