CREATE TABLE "pushup_habit_daily_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pushup_habit_daily_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"habit_id" integer NOT NULL,
	"user_id" text NOT NULL,
	"log_date" date NOT NULL,
	"entry" text NOT NULL,
	"habit_log_id" integer,
	"duration" integer,
	"action_value" integer,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "is_timer_based" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "timer_duration" integer;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "min_action_required" text;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "min_action_value" integer;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "min_action_unit" text;--> statement-breakpoint
ALTER TABLE "pushup_habit" ADD COLUMN "current_status" text DEFAULT 'not_started' NOT NULL;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD COLUMN "status" text DEFAULT 'not_done' NOT NULL;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD COLUMN "action_value" integer;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD COLUMN "timer_started_at" timestamp;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD COLUMN "timer_completed_at" timestamp;--> statement-breakpoint
ALTER TABLE "pushup_habit_log" ADD COLUMN "timer_duration" integer;--> statement-breakpoint
ALTER TABLE "pushup_habit_daily_log" ADD CONSTRAINT "pushup_habit_daily_log_habit_id_pushup_habit_id_fk" FOREIGN KEY ("habit_id") REFERENCES "public"."pushup_habit"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_habit_daily_log" ADD CONSTRAINT "pushup_habit_daily_log_user_id_pushup_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pushup_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pushup_habit_daily_log" ADD CONSTRAINT "pushup_habit_daily_log_habit_log_id_pushup_habit_log_id_fk" FOREIGN KEY ("habit_log_id") REFERENCES "public"."pushup_habit_log"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "daily_log_habit_id_idx" ON "pushup_habit_daily_log" USING btree ("habit_id");--> statement-breakpoint
CREATE INDEX "daily_log_user_date_idx" ON "pushup_habit_daily_log" USING btree ("user_id","log_date");--> statement-breakpoint
CREATE INDEX "habit_user_id_idx" ON "pushup_habit" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "habit_log_user_date_idx" ON "pushup_habit_log" USING btree ("user_id","checkin_date");--> statement-breakpoint
ALTER TABLE "pushup_user" DROP COLUMN "role";--> statement-breakpoint
ALTER TABLE "pushup_user" DROP COLUMN "banned";--> statement-breakpoint
ALTER TABLE "pushup_user" DROP COLUMN "ban_reason";--> statement-breakpoint
ALTER TABLE "pushup_user" DROP COLUMN "ban_expires";